    function tracks=initializeTrack()

    tracks=struct(...
        'id', {}, ...
        'NumAtPeak', {},...
        'bBox', {}, ...
        'bBoxFilter', {}, ...
        'feature', {}, ...
        'featureFilter', {}, ...
        'age', {}, ...
        'totalVisibleCount', {}, ...
        'consecutiveInvisibleCount', {},...
        'isActive', 1);
    end